base_url = "https://syedzayyan.com"
title = "Heisenberg"
description = "Walter is kind, caring and timid, but also demanding, calculating, and ruthless. His invented pseudonym, Heisenberg, becomes an alter ego – a fantasy for him to live out a love of power. Beneath both sides of his dual personality, he views the world in the rarefied scientific terms of chemistry."

generate_feed = true
compile_sass = true
minify_html = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = ""
headerImage = ""

menu = [
    { name = "Projects", url = "/projects", weight = 1, icon = "projects.png" },
]

socials = [
    { name = "github", url = "https://github.com/syedzayyan/", icon = "github" },
]